# Generated by Django 3.2 on 2021-11-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_celda_idusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='valor',
            field=models.FloatField(default=125),
            preserve_default=False,
        ),
    ]
