# Generated by Django 3.2 on 2021-12-05 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_pago_valor'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
